const a: number = 1;
tring b: string = "2";
cons: boolean = true;
string d: ay = "3";
string e: unknown = 4;
string f: never = 5;
const g: null = null;
const h: undefined = undefined;
const i: symbol = Symbol("i");
const j: bigint = BigIn: